<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MeitalDaniel-PC" ignored="0" name="Test" tests="22" failures="4" timestamp="2020-06-15T17:47:44 IDT" time="78.349" errors="0">
  <testcase name="T01_invalidLoginAttempts" time="2.292" classname="TestCases.Login_Test"/>
  <testcase name="T01_invalidLoginAttempts" time="2.268" classname="TestCases.Login_Test"/>
  <testcase name="T01_invalidLoginAttempts" time="2.257" classname="TestCases.Login_Test"/>
  <testcase name="T01_invalidLoginAttempts" time="2.316" classname="TestCases.Login_Test"/>
  <testcase name="T01_invalidLoginAttempts" time="2.353" classname="TestCases.Login_Test"/>
  <testcase name="T01_successfulLogin" time="0.984" classname="TestCases.Login_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Products] but found [Products_123123]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Products] but found [Products_123123]
at TestCases.Login_Test.T01_successfulLogin(Login_Test.java:67)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- T01_successfulLogin -->
  <testcase name="T01_validLogin" time="0.793" classname="TestCases.Products_Test"/>
  <testcase name="T02_getPageTitle" time="0.041" classname="TestCases.Products_Test"/>
  <testcase name="T03_addItemsToCart_1" time="2.475" classname="TestCases.Products_Test"/>
  <testcase name="T03_addItemsToCart_2" time="2.391" classname="TestCases.Products_Test"/>
  <testcase name="T03_addItemsToCart_3" time="2.534" classname="TestCases.Products_Test"/>
  <testcase name="T03_addItemsToCart_4" time="2.411" classname="TestCases.Products_Test"/>
  <testcase name="T03_addItemsToCart_5" time="2.338" classname="TestCases.Products_Test"/>
  <testcase name="T03_addItemsToCart_6" time="0.48" classname="TestCases.Products_Test">
    <failure type="java.lang.AssertionError" message="expected [6] but found [7]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [7]
at TestCases.Products_Test.T03_addItemsToCart_6(Products_Test.java:152)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- T03_addItemsToCart_6 -->
  <testcase name="T01_validLogin" time="0.678" classname="TestCases.Cart_Test"/>
  <testcase name="T02_selectSingleItem" time="0.342" classname="TestCases.Cart_Test"/>
  <testcase name="T03_continueToCheckout" time="0.985" classname="TestCases.Cart_Test"/>
  <testcase name="T01_validLogin" time="0.666" classname="TestCases.Checkout_Test"/>
  <testcase name="T02_selectSingleItem" time="0.37" classname="TestCases.Checkout_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1] but found [3]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1] but found [3]
at TestCases.Checkout_Test.T02_selectSingleItem(Checkout_Test.java:67)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- T02_selectSingleItem -->
  <testcase name="T03_continueToCheckout" time="3.171" classname="TestCases.Checkout_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1] but found [3],
	expected [15.99] but found [15.99_123]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1] but found [3],
expected [15.99] but found [15.99_123]
at TestCases.Checkout_Test.T03_continueToCheckout(Checkout_Test.java:80)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- T03_continueToCheckout -->
  <testcase name="T04_checkout_StepOne" time="6.798" classname="TestCases.Checkout_Test"/>
  <testcase name="T05_checkout_StepTwo" time="0.263" classname="TestCases.Checkout_Test"/>
</testsuite> <!-- Test -->
